/*
 * (C) Copyright 2017 ikwzm
 *
 * Configuration for Zynq Development Board - PYNQ-Z1
 * See zynq-common.h for Zynq common configs
 *
 * SPDX-License-Identifier:	GPL-2.0+
 */

#ifndef __CONFIG_ZYNQ_PYNQZ1_H
#define __CONFIG_ZYNQ_PYNQZ1_H

#define CONFIG_SYS_NO_FLASH

#define CONFIG_ZYNQ_USB
#define CONFIG_ZYNQ_I2C0

/*
#define CONFIG_ZYNQ_I2C1
#define CONFIG_SYS_I2C_EEPROM_ADDR_LEN	1
#define CONFIG_CMD_EEPROM
#define CONFIG_ZYNQ_GEM_EEPROM_ADDR	0x50
#define CONFIG_ZYNQ_GEM_I2C_MAC_OFFSET	0xFA
#define CONFIG_DISPLAY
#define CONFIG_I2C_EDID
*/

/* GEM MAC address offset */
#define CONFIG_ZYNQ_GEM_SPI_MAC_OFFSET	0x20

/* Define ARTY-Z PS Clock Frequency to 50MHz */
#define CONFIG_ZYNQ_PS_CLK_FREQ	50000000UL

/* default config parameters for zynq boards */
#include <configs/zynq-common.h>

#ifdef CONFIG_BOOTARGS
#undef CONFIG_BOOTARGS
#endif

#ifdef CONFIG_BOOTCOMMAND
#undef CONFIG_BOOTCOMMAND
#endif

/*
 * Be aware that this file is included by an autogenerated header file,
 * 'include/config.h' after the default zynq header, hence the #ifdef #undef 
 * statements.
*/
#define CONFIG_BOOTARGS "console=ttyPS0,115200n8 root=/dev/mmcblk0p2 rw rootfstype=ext4\0"
#define CONFIG_BOOTCOMMAND "fatload mmc 0:1 0x08020000 uImage;fatload mmc 0:1 0x18D7130 zynq-pynqz1.dtb;bootm 0x08020000 - 0x18D7130\0"

#endif /* __CONFIG_ZYNQ_PYNQZ1_H */
